[package]
name = "ardfevent_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "ardfevent_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["chrono"] }
chrono = "0.4"
itertools = "0.12"
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }

